### ISSUE TITLE
incorrect / incomplete docstring in instability_analysis_from_N2_profile

### ISSUE THREAD

**Issue by rabernat** [rabernat/oceanmodes#5]
The actual arguments to `instability_analysis_from_N2_profile` are not consistent with the docstring.

cc: @roxyboy

**Comment by roxyboy** [comment]
Amended the docstring.

**Comment by rabernat** [comment]
You should reference this issue in your pull request (#7)

**Comment by roxyboy** [comment]
The pull request number is 81dc8f1

**Comment by rabernat** [comment]
> The pull request number is 81dc8f1

No it is not. That is the commit number. The pull request is #7.
