### ISSUE TITLE
The num keyword doesn't work in instability_analysis_from_N2_profile

### ISSUE THREAD

**Issue by rabernat** [rabernat/oceanmodes#6]
The function accepts the parameter `num`.

But the number of eigenmodes returned is hardcoded at 4.
https://github.com/rabernat/oceanmodes/blob/master/oceanmodes/baroclinic.py#L382

**Comment by roxyboy** [comment]
Fixed it so that the number of eigenmodes returned can change with the parameter `num`.

**Comment by rabernat** [comment]
Where did you fix it? In your pull request? If so, you can refer to your pull request from this issue: #7

**Comment by roxyboy** [comment]
The pull request number is 3a14d8f

**Comment by rabernat** [comment]
> The pull request number is 3a14d8f

No it is not. The pull request is #7.
